### ISSUE TITLE
Calling a url with an arbitrary ticket querystring should not raise a 500 error

### ISSUE THREAD

**Issue by cirotix** [briefmnews/django-esidoc#18]
## Current behavior 
When a user goes on a page and manually add a `ticket` querystring, a 500 error is raised

## Expected behavior
This querystring should be discarded and the required page regularly displayed.

## How to reproduce
https://www.brief.me/?ticket=123

**Comment by ThomSawyer** [comment]
Done

**Comment by eespanel** [comment]
I trust you.
